### ISSUE TITLE
"--output" arg seems to incorrectly nest output filepath

### ISSUE THREAD

**Issue by arrowtype** [jenskutilek/glyphspkg#1]
First, thank you for making this library! It is already proving to be so helpful, especially in [a Makefile similar to your recommendation](https://forum.glyphsapp.com/t/documentation-on-the-glyphspackage-format/23435/5).

However, I think I may have come across an unintended result, so I wanted to report it.

Context:
- I have an input, `sources/shantellsans-wght_ital_IRGL.glyphspackage`
- I want an output to go into a `build-prep` folder
- Therefore, I am adding the arg `-o sources/build-prep/shantellsans-wght_ital_IRGL.glyphs`

Unexpected result:
- glyphspkg seems to want to nest the provided output path into the default path, like: `fontdir/familyname.glyphs/familyname.glyphs`

Here’s the full traceback:

```
▶ glyphspkg sources/shantellsans-wght_ital_IRGL.glyphspackage -o sources/build-prep/shantellsans-wght_ital_IRGL.glyphs
Reading: sources/shantellsans-wght_ital_IRGL.glyphspackage
Saving: sources/build-prep/shantellsans-wght_ital_IRGL.glyphs/shantellsans-wght_ital_IRGL.glyphs
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/shantell-sans/venv/bin/glyphspkg", line 8, in <module>
    sys.exit(main())
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/glyphspkg/cmdline.py", line 48, in main
    package_to_single(input_path, arguments.output_path)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/glyphspkg/package_to_single.py", line 51, in package_to_single
    save_to_plist_path(glyphs_file, output_file_path)
  File "/Users/stephennixon/type-repos/shantell-sans/venv/lib/python3.10/site-packages/glyphspkg/plist.py", line 15, in save_to_plist_path
    with codecs.open(plist_path, "wb", "utf-8") as f:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'sources/build-prep/shantellsans-wght_ital_IRGL.glyphs/shantellsans-wght_ital_IRGL.glyphs'
```

This happens whether I try to run glyphspkg from the command line or from a Makefile. I might be doing something wrong, but I don’t _think_ I am...

Thanks again!

**Comment by jenskutilek** [comment]
Good catch!

I think I expected the `-o` option to contain a directory path, not full file path, because it is possible to supply multiple input files on the command line. If a full output file path is supplied, then each input file would overwrite that file when it is converted.

Anyway, I improved the logic so that in this constellation, an error message is issued, while all other cases (including yours) should now be handled correctly.

Fixed in 196497f0abb4b794ac91b275a1939ad2ccb4585d, but I had some troubles with the GitHub actions to publish, so that the release version to use is now [0.1.7 via PyPI.](https://pypi.org/project/glyphspkg/0.1.7/)

**Comment by jenskutilek** [comment]
To make it more clear, as your file name doesn’t change (glyphspkg automatically changes the suffix to `.glyphs`), you could have used this option on the command line:

```bash
glyphspkg -o sources/build-prep/ sources/shantellsans-wght_ital_IRGL.glyphspackage
```

**Comment by arrowtype** [comment]
Awesome, thanks @jenskutilek!
